### ISSUE TITLE
HTML Text Extraction Readability on PPCT

### ISSUE THREAD

**Issue by FairWalkTeam** [ITSec-WWU-Munster/Unifying-Privacy-Policy-Detection#2] opened 2021-11-02 20:42 UTC
Hi, thank you for developing this great tool and making it open source. 
I follow the guild on readme, and run the demo under Unifying-Privacy-Policy-Detection/privacy_policy_link_detection successfully.
However, when testing under Unifying-Privacy-Policy-Detection/privacy_policy_toolchain/code with the command `python ppt.py ../../privacy_policy_link_detection/datadir/privacy_policies/`, i ran into the problem. Do you have any ideas? 

> Encoding Detection: 100%|############################################################################################################################| 4/4 [00:00<00:00, 35.38it/s]
Text Extraction NumWordsRules: 100%|###############################################################################################################| 4/4 [00:00<00:00, 1774.43it/s]
HTML Text Extraction Canola: 100%|#################################################################################################################| 4/4 [00:00<00:00, 2649.17it/s]
HTML Text Extraction Readability:   0%|                                                                                                                      | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
  File "ppt.py", line 886, in <module>
    text_extraction_module()
  File "ppt.py", line 312, in text_extraction_module
    for raw_html in tqdm(list_of_raw_html_pages, desc="HTML Text Extraction Readability")
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "ppt.py", line 250, in text_from_html_extraction_readability
    result = simple_json_from_html_string(raw_html, use_readability=True)
  File "/home/anaconda3/envs/pptc/lib/python3.6/site-packages/readabilipy/simple_json.py", line 38, in simple_json_from_html_string
    f.write(html)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 43542-43545: ordinal not in range(128)
HTML Text Extraction Readability:   0%|                                                                                                                      | 0/4 [00:00<?, ?it/s]

**Comment by g3rfx** [comment] 2021-11-09 12:29
Hi,

This seems to be rather an issue arising from the following function of readabilipy:
https://github.com/alan-turing-institute/ReadabiliPy/blob/ea5926d5b5c166e66cd886d380ffce5c85ef9ad3/readabilipy/simple_json.py#L37

Is there the possibility to share the 4 HTML files on which you performed the test so that I can take a closer look?

**Comment by ruiyeNLP** [comment] 2021-11-17 15:45
Sure.

Here is the folder of [datadir/privacypolices](https://drive.google.com/drive/folders/1tLDIsjfCkbZPX1P_lOgnl804CdR_8lYl?usp=sharing) as mentioned in Unifying-Privacy-Policy-Detection/privacy_policy_link_detection/README.md. It containd the 4 html files. Please take a closer look.

**Comment by g3rfx** [comment] 2021-11-18 09:30
Thanks for sharing the data. (Un)fortunately, I could not reproduce the UnicodeEncodeError. I have uploaded the logfile and the resulting database file [here](https://drive.google.com/drive/folders/1S9kzR5xUZrljZblrtK0VSJ0kClmvxSkQ?usp=sharing).

Might it be the case that your [locale ](https://stackoverflow.com/questions/51026315/how-to-solve-unicodedecodeerror-in-python-3-6/51027262#51027262)is not set to "UTF-8"? The output of `locale `on my Ubuntu system looks like this:
```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by ruiyeNLP** [comment] 2021-11-18 09:58
Here is my `locale` result.

`LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

**Comment by g3rfx** [comment] 2022-01-07 09:51
This thread provides interesting information:
https://stackoverflow.com/questions/55673886/what-is-the-difference-between-c-utf-8-and-en-us-utf-8-locales/55693338

**Comment by ruiyeNLP** [comment] 2022-01-07 10:54
Thanks a lot for the info. Sorry for the late reply. I made it work several days ago by modifying `locale` with `export LC_ALL=C.UTF-8` and `export LANG=C.UTF-8`.

**Comment by g3rfx** [comment] 2022-01-10 07:49
That is good news. I close the issue.

**Closed as completed by g3rfx** 2022-01-10 07:49 UTC
